<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use App\Region;

class RegionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $regions = [
            [
                'mre_id' => 'RG0001',
                'mre_desc' => 'Nanggroe Aceh Darussalam',
                'mre_status' => '1',
                'mre_create_user' => 'Super Admin',
                'mre_create_date' => Carbon::now()->toDateTimeString(),
                'mre_update_user' => 'Super Admin',
                'mre_update_date' => Carbon::now()->toDateTimeString(),
            ],
            [
                'mre_id' => 'RG0002',
                'mre_desc' => 'Sumatera Utara',
                'mre_status' => '1',
                'mre_create_user' => 'Super Admin',
                'mre_create_date' => Carbon::now()->toDateTimeString(),
                'mre_update_user' => 'Super Admin',
                'mre_update_date' => Carbon::now()->toDateTimeString(),
            ],
            [
                'mre_id' => 'RG0003',
                'mre_desc' => 'Sumatera Selatan',
                'mre_status' => '1',
                'mre_create_user' => 'Super Admin',
                'mre_create_date' => Carbon::now()->toDateTimeString(),
                'mre_update_user' => 'Super Admin',
                'mre_update_date' => Carbon::now()->toDateTimeString(),
            ],
            [
                'mre_id' => 'RG0004',
                'mre_desc' => 'Sumatera Barat',
                'mre_status' => '1',
                'mre_create_user' => 'Super Admin',
                'mre_create_date' => Carbon::now()->toDateTimeString(),
                'mre_update_user' => 'Super Admin',
                'mre_update_date' => Carbon::now()->toDateTimeString(),
            ],
            [
                'mre_id' => 'RG0005',
                'mre_desc' => 'Bengkulu',
                'mre_status' => '1',
                'mre_create_user' => 'Super Admin',
                'mre_create_date' => Carbon::now()->toDateTimeString(),
                'mre_update_user' => 'Super Admin',
                'mre_update_date' => Carbon::now()->toDateTimeString(),
            ],
            [
                'mre_id' => 'RG0006',
                'mre_desc' => 'Riau',
                'mre_status' => '1',
                'mre_create_user' => 'Super Admin',
                'mre_create_date' => Carbon::now()->toDateTimeString(),
                'mre_update_user' => 'Super Admin',
                'mre_update_date' => Carbon::now()->toDateTimeString(),
            ],
            [
                'mre_id' => 'RG0007',
                'mre_desc' => 'Kepulauan Riau',
                'mre_status' => '1',
                'mre_create_user' => 'Super Admin',
                'mre_create_date' => Carbon::now()->toDateTimeString(),
                'mre_update_user' => 'Super Admin',
                'mre_update_date' => Carbon::now()->toDateTimeString(),
            ],
            [
                'mre_id' => 'RG0008',
                'mre_desc' => 'Jambi',
                'mre_status' => '1',
                'mre_create_user' => 'Super Admin',
                'mre_create_date' => Carbon::now()->toDateTimeString(),
                'mre_update_user' => 'Super Admin',
                'mre_update_date' => Carbon::now()->toDateTimeString(),
            ],
            [
                'mre_id' => 'RG0009',
                'mre_desc' => 'Lampung',
                'mre_status' => '1',
                'mre_create_user' => 'Super Admin',
                'mre_create_date' => Carbon::now()->toDateTimeString(),
                'mre_update_user' => 'Super Admin',
                'mre_update_date' => Carbon::now()->toDateTimeString(),
            ],
            [
                'mre_id' => 'RG0010',
                'mre_desc' => 'Bangka Belitung',
                'mre_status' => '1',
                'mre_create_user' => 'Super Admin',
                'mre_create_date' => Carbon::now()->toDateTimeString(),
                'mre_update_user' => 'Super Admin',
                'mre_update_date' => Carbon::now()->toDateTimeString(),
            ],
            [
                'mre_id' => 'RG0011',
                'mre_desc' => 'Kalimantan Barat',
                'mre_status' => '1',
                'mre_create_user' => 'Super Admin',
                'mre_create_date' => Carbon::now()->toDateTimeString(),
                'mre_update_user' => 'Super Admin',
                'mre_update_date' => Carbon::now()->toDateTimeString(),
            ],
            [
                'mre_id' => 'RG0012',
                'mre_desc' => 'Kalimantan Timur',
                'mre_status' => '1',
                'mre_create_user' => 'Super Admin',
                'mre_create_date' => Carbon::now()->toDateTimeString(),
                'mre_update_user' => 'Super Admin',
                'mre_update_date' => Carbon::now()->toDateTimeString(),
            ],
            [
                'mre_id' => 'RG0013',
                'mre_desc' => 'Kalimantan Selatan',
                'mre_status' => '1',
                'mre_create_user' => 'Super Admin',
                'mre_create_date' => Carbon::now()->toDateTimeString(),
                'mre_update_user' => 'Super Admin',
                'mre_update_date' => Carbon::now()->toDateTimeString(),
            ],
            [
                'mre_id' => 'RG0014',
                'mre_desc' => 'Kalimantan Tengah',
                'mre_status' => '1',
                'mre_create_user' => 'Super Admin',
                'mre_create_date' => Carbon::now()->toDateTimeString(),
                'mre_update_user' => 'Super Admin',
                'mre_update_date' => Carbon::now()->toDateTimeString(),
            ],
            [
                'mre_id' => 'RG0015',
                'mre_desc' => 'Kalimantan Utara',
                'mre_status' => '1',
                'mre_create_user' => 'Super Admin',
                'mre_create_date' => Carbon::now()->toDateTimeString(),
                'mre_update_user' => 'Super Admin',
                'mre_update_date' => Carbon::now()->toDateTimeString(),
            ],
            [
                'mre_id' => 'RG0016',
                'mre_desc' => 'Banten',
                'mre_status' => '1',
                'mre_create_user' => 'Super Admin',
                'mre_create_date' => Carbon::now()->toDateTimeString(),
                'mre_update_user' => 'Super Admin',
                'mre_update_date' => Carbon::now()->toDateTimeString(),
            ],
            [
                'mre_id' => 'RG0017',
                'mre_desc' => 'DKI Jakarta',
                'mre_status' => '1',
                'mre_create_user' => 'Super Admin',
                'mre_create_date' => Carbon::now()->toDateTimeString(),
                'mre_update_user' => 'Super Admin',
                'mre_update_date' => Carbon::now()->toDateTimeString(),
            ],
            [
                'mre_id' => 'RG0018',
                'mre_desc' => 'Jawa Barat',
                'mre_status' => '1',
                'mre_create_user' => 'Super Admin',
                'mre_create_date' => Carbon::now()->toDateTimeString(),
                'mre_update_user' => 'Super Admin',
                'mre_update_date' => Carbon::now()->toDateTimeString(),
            ],
            [
                'mre_id' => 'RG0019',
                'mre_desc' => 'Jawa Tengah',
                'mre_status' => '1',
                'mre_create_user' => 'Super Admin',
                'mre_create_date' => Carbon::now()->toDateTimeString(),
                'mre_update_user' => 'Super Admin',
                'mre_update_date' => Carbon::now()->toDateTimeString(),
            ],
            [
                'mre_id' => 'RG0020',
                'mre_desc' => 'Yogyakarta',
                'mre_status' => '1',
                'mre_create_user' => 'Super Admin',
                'mre_create_date' => Carbon::now()->toDateTimeString(),
                'mre_update_user' => 'Super Admin',
                'mre_update_date' => Carbon::now()->toDateTimeString(),
            ],
            [
                'mre_id' => 'RG0021',
                'mre_desc' => 'Jawa Timur',
                'mre_status' => '1',
                'mre_create_user' => 'Super Admin',
                'mre_create_date' => Carbon::now()->toDateTimeString(),
                'mre_update_user' => 'Super Admin',
                'mre_update_date' => Carbon::now()->toDateTimeString(),
            ],
            [
                'mre_id' => 'RG0022',
                'mre_desc' => 'Bali',
                'mre_status' => '1',
                'mre_create_user' => 'Super Admin',
                'mre_create_date' => Carbon::now()->toDateTimeString(),
                'mre_update_user' => 'Super Admin',
                'mre_update_date' => Carbon::now()->toDateTimeString(),
            ],
            [
                'mre_id' => 'RG0023',
                'mre_desc' => 'Nusa Tenggara Barat',
                'mre_status' => '1',
                'mre_create_user' => 'Super Admin',
                'mre_create_date' => Carbon::now()->toDateTimeString(),
                'mre_update_user' => 'Super Admin',
                'mre_update_date' => Carbon::now()->toDateTimeString(),
            ],
            [
                'mre_id' => 'RG0024',
                'mre_desc' => 'Nusa Tenggara Timur',
                'mre_status' => '1',
                'mre_create_user' => 'Super Admin',
                'mre_create_date' => Carbon::now()->toDateTimeString(),
                'mre_update_user' => 'Super Admin',
                'mre_update_date' => Carbon::now()->toDateTimeString(),
            ],
            [
                'mre_id' => 'RG0025',
                'mre_desc' => 'Gorontalo',
                'mre_status' => '1',
                'mre_create_user' => 'Super Admin',
                'mre_create_date' => Carbon::now()->toDateTimeString(),
                'mre_update_user' => 'Super Admin',
                'mre_update_date' => Carbon::now()->toDateTimeString(),
            ],
            [
                'mre_id' => 'RG0026',
                'mre_desc' => 'Sulawesi Barat',
                'mre_status' => '1',
                'mre_create_user' => 'Super Admin',
                'mre_create_date' => Carbon::now()->toDateTimeString(),
                'mre_update_user' => 'Super Admin',
                'mre_update_date' => Carbon::now()->toDateTimeString(),
            ],
            [
                'mre_id' => 'RG0027',
                'mre_desc' => 'Sulawesi Tengah',
                'mre_status' => '1',
                'mre_create_user' => 'Super Admin',
                'mre_create_date' => Carbon::now()->toDateTimeString(),
                'mre_update_user' => 'Super Admin',
                'mre_update_date' => Carbon::now()->toDateTimeString(),
            ],
            [
                'mre_id' => 'RG0028',
                'mre_desc' => 'Sulawesi Utara',
                'mre_status' => '1',
                'mre_create_user' => 'Super Admin',
                'mre_create_date' => Carbon::now()->toDateTimeString(),
                'mre_update_user' => 'Super Admin',
                'mre_update_date' => Carbon::now()->toDateTimeString(),
            ],
            [
                'mre_id' => 'RG0029',
                'mre_desc' => 'Sulawesi Tenggara',
                'mre_status' => '1',
                'mre_create_user' => 'Super Admin',
                'mre_create_date' => Carbon::now()->toDateTimeString(),
                'mre_update_user' => 'Super Admin',
                'mre_update_date' => Carbon::now()->toDateTimeString(),
            ],
            [
                'mre_id' => 'RG0030',
                'mre_desc' => 'Sulawesi Selatan',
                'mre_status' => '1',
                'mre_create_user' => 'Super Admin',
                'mre_create_date' => Carbon::now()->toDateTimeString(),
                'mre_update_user' => 'Super Admin',
                'mre_update_date' => Carbon::now()->toDateTimeString(),
            ],
            [
                'mre_id' => 'RG0031',
                'mre_desc' => 'Maluku Utara',
                'mre_status' => '1',
                'mre_create_user' => 'Super Admin',
                'mre_create_date' => Carbon::now()->toDateTimeString(),
                'mre_update_user' => 'Super Admin',
                'mre_update_date' => Carbon::now()->toDateTimeString(),
            ],
            [
                'mre_id' => 'RG0032',
                'mre_desc' => 'Maluku',
                'mre_status' => '1',
                'mre_create_user' => 'Super Admin',
                'mre_create_date' => Carbon::now()->toDateTimeString(),
                'mre_update_user' => 'Super Admin',
                'mre_update_date' => Carbon::now()->toDateTimeString(),
            ],
            [
                'mre_id' => 'RG0033',
                'mre_desc' => 'Papua Barat',
                'mre_status' => '1',
                'mre_create_user' => 'Super Admin',
                'mre_create_date' => Carbon::now()->toDateTimeString(),
                'mre_update_user' => 'Super Admin',
                'mre_update_date' => Carbon::now()->toDateTimeString(),
            ],
            [
                'mre_id' => 'RG0034',
                'mre_desc' => 'Papua',
                'mre_status' => '1',
                'mre_create_user' => 'Super Admin',
                'mre_create_date' => Carbon::now()->toDateTimeString(),
                'mre_update_user' => 'Super Admin',
                'mre_update_date' => Carbon::now()->toDateTimeString(),
            ],
        ];

        foreach ($regions as $key => $val) {
            Region::create($val);
        }
    }
}
